#########################
## Rules -> http://palantir.github.io/tslint/rules/
## Severity 0 (disabled)
## Severity 1 (warning)
## Severity 2 (error)
#########################
# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
  # Set the formatter to 'stylish'
  #formatter: stylish
  formatter: 'checkstyle'
  # Output file instead of logging results
  output-file: 'sassLintResult.xml'

# Rule Configuration
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  mixins-before-declarations:
    - 2
    - exclude:
        - breakpoint
        - mq

  no-warn: 1
  no-debug: 1
  no-ids: 2
  no-important: 1
  hex-notation:
    - 2
    - style: uppercase
  indentation:
    - 1
    - size: 2
  quotes:
    - 1
    - style: single
